name: kernelCTF test action
on:
  workflow_dispatch:
  push: # hack to make this workflow appear on the UI
permissions: {}
jobs:
  cpu_info:
    runs-on: ubuntu-22.04-4core
    steps:
      - name: KPTI check
        run: |
          cat /proc/cpuinfo|grep " pti"
          sudo dmesg | grep 'Kernel/User page tables isolation'
          cat /sys/devices/system/cpu/vulnerabilities/meltdown
          dmesg | grep isolation

      - name: cpuinfo
        run: cat /proc/cpuinfo

      - name: dmesg
        run: dmesg
